### ISSUE TITLE
Failed to start the concentrator with kernel 6.6.22 (Pi 4B Bookworm + SX130X)

### ISSUE THREAD

**Issue by timiman** [Lora-net/sx1302_hal#120]
I'm unable to start a SX130X as concentrator under kernel 6.6.22 on a Pi 4B.
Running reset_lgw.sh, outputs:
`./reset_lgw.sh: 26: echo: echo: I/O error
./reset_lgw.sh: 27: echo: echo: I/O error
./reset_lgw.sh: 28: echo: echo: I/O error
./reset_lgw.sh: 29: echo: echo: I/O error
./reset_lgw.sh: 32: cannot create /sys/class/gpio/gpio17/direction: Directory nonexistent
./reset_lgw.sh: 33: cannot create /sys/class/gpio/gpio22/direction: Directory nonexistent
./reset_lgw.sh: 34: cannot create /sys/class/gpio/gpio18/direction: Directory nonexistent
./reset_lgw.sh: 35: cannot create /sys/class/gpio/gpio13/direction: Directory nonexistent
CoreCell reset through GPIO17...
SX1261 reset through GPIO17...
CoreCell power enable through GPIO18...
CoreCell ADC reset through GPIO13...
./reset_lgw.sh: 45: cannot create /sys/class/gpio/gpio18/value: Directory nonexistent
./reset_lgw.sh: 47: cannot create /sys/class/gpio/gpio17/value: Directory nonexistent
./reset_lgw.sh: 48: cannot create /sys/class/gpio/gpio17/value: Directory nonexistent
./reset_lgw.sh: 50: cannot create /sys/class/gpio/gpio22/value: Directory nonexistent
./reset_lgw.sh: 51: cannot create /sys/class/gpio/gpio22/value: Directory nonexistent
./reset_lgw.sh: 53: cannot create /sys/class/gpio/gpio13/value: Directory nonexistent
./reset_lgw.sh: 54: cannot create /sys/class/gpio/gpio13/value: Directory nonexistent`

By default the reset GPIO pin was pointing to 23, but found that 17 is the correct one for this SX130X.
It seems like the GPIO number has changed for 6.6.22 , as I'm getting:
`grep -s . /sys/class/gpio/gpiochip*/*
/sys/class/gpio/gpiochip512/base:512
/sys/class/gpio/gpiochip512/label:pinctrl-bcm2711
/sys/class/gpio/gpiochip512/ngpio:58
/sys/class/gpio/gpiochip570/base:570
/sys/class/gpio/gpiochip570/label:raspberrypi-exp-gpio
/sys/class/gpio/gpiochip570/ngpio:8`

User running all above is in group 'gpio'.

Does the reset_lgw.sh needs changes to work with new GPIO numbering ?

**Comment by wildekek** [comment]
Just for confirmation: I just ran into the same issue.
[Edit] Seems like GPIO sysfs is deprecated and superseded by libgpiod. We can make a patch to fix the sysfs paths for now, but support for this will likely end in the near future.
https://waldorf.waveform.org.uk/2022/the-one-where-dave-breaks-stuff.html

**Comment by timiman** [comment]
I've seen that article too.
I've also sent a tech support to waveshare.

**Comment by wildekek** [comment]
Looks like it is fairly trivial to use the gpiod command line tools for the reset script:
https://manpages.debian.org/experimental/gpiod/index.html

I'll give that a go and let you know if that fixes everything.

**Comment by wildekek** [comment]
I think that this repo should be marked as deprecated.

I switched to Basic Station using [this repo](https://github.com/xoseperez/basicstation-docker) which supports libgpiod.

working docker-compose example for your convenience:
```
services:

  basicstation:
    image: xoseperez/basicstation:latest
    container_name: basicstation
    restart: unless-stopped
    privileged: true
    network_mode: host      # required to read main interface MAC instead of virtual one
    environment:
      MODEL: "WM1302"
      DEVICE: "AUTO"
      USE_LIBGPIOD: 1
      RESET_GPIO: 17
      POWER_EN_GPIO: 18
      TC_KEY: "***"
      CUPS_KEY: "***"
      SERVER: "***"
```
